export rule1 = [{.开通},{.d1},{.d2},{.功能}]
export rule2 = [{.查询},{.d1},{.d2}]
export rule3 = [{.d1},{.d2},{.开通}]
export rule4 = [{.开通},{.d1},{.d2}]
export rule5 = [{.d1},{.d2},{.功能},{.开通}]
export rule6 = [{.d1},{.d2},{.查询}]
export rule7 = [{.查询},{.d1},{.d2},{.使用情况}]
export rule8 = [{.查询},{.d1},{.d2},{.功能}]
